"""expand student fields

Revision ID: 7c07f3701f79
Revises: 
Create Date: 2025-05-30 16:52:13.669930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c07f3701f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('father_phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mother_phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('mother_phone')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_phone')
        batch_op.drop_column('father_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('school')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
